# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at 2015 daily
    - cron: '50 19 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e76a59e608473282acbf54f